#name:
#  user-srv
#
#mysql:
#  host: 192.168.1.101
#  port: 3306
#  user: root
#  password: 1234qwer!
#  db: mxshop_userop_srv
#
#consul:
#  host: 192.168.1.101
#  port: 8500

host: 192.168.0.101
port: 8848
namespaceId: b108abeb-b7e7-4599-9c4d-b050dd729979
dataId: userop-srv.json
group: dev