// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_CODE_OK-1]
	_ = x[ERR_CODE_INVALID-2]
	_ = x[ERR_CODE_TIMEOUT-3]
}

const _ErrCode_name = "成功参数错误超时"

var _ErrCode_index = [...]uint8{0, 6, 18, 24}

func (i ErrCode) String() string {
	i -= 1
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
