#name:
#  user-srv
#
#mysql:
#  host: 192.168.1.101
#  port: 3306
#  user: root
#  password: 1234qwer!
#  db: mxshop_order_srv
#
#consul:
#  host: 192.168.1.101
#  port: 8500

host: 192.168.0.101
port: 8848
namespaceId: ec409bb2-b7df-4dcf-a727-d886af98f6ad
dataId: order-srv.json
group: dev